---
title: "calculating_pa"
output: html_document
date: "2024-07-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(dplyr)
library(purrr)



eth<- read.csv("eth_nar.csv")
ind<- read.csv("ind_nar.csv") 
nga<- read.csv("nga_nar.csv")

```


```{r}
# storing EAR values from Allen et al. (2019)

ear_values<- c(vita_rae_mcg = 490, thia_mg = 0.9, ribo_mg = 1.3, niac_mg = 11, vitb6_mg = 1.3, folate_mcg = 250, vitb12_mcg = 2, fe_mg = 22.4, zn_mg = 10.2)
```

# Calculating PA and MPA - Ethiopia
## Creating a dataframe of intakes and hhid
```{r}

# ETHIOPIA dataframe with hhid, calorific intake and micronutrient intake 
df <- eth %>% 
  select(hhid, energy_kcal, vita_rae_mcg, thia_mg, ribo_mg, niac_mg, vitb6_mg, folate_mcg, vitb12_mcg, fe_mg, zn_mg)

```


```{r}
# creating allen_ear df
allen_ear <- data.frame(
  nutrient = c('vita_rae_mcg', 'thia_mg', 'ribo_mg', 'niac_mg', 'vitb6_mg', 'folate_mcg', 'vitb12_mcg', 'fe_mg', 'zn_mg'),
  ear_value = c(490, 0.9, 1.3, 11, 1.3, 250, 2, 22.4, 10.2) 
)

# Calculate standard deviation based on nutrient-specific rules
allen_ear <- allen_ear %>%
  mutate(sd = case_when(
    nutrient == "vita_rae_mcg" ~ 0.2 * ear_value,
    nutrient == "niac_mg" ~ 0.15 * ear_value,
    TRUE ~ 0.1 * ear_value
  ))

```

# Creating a function to calculate PA 
```{r}
calculate_adequacy_prob <- function(ref_value, micronutrient, number_dist = 1000){
  
  micronutrient_normal <- function(micronutrient){
    y <- allen_ear %>% 
      filter(nutrient %in% c(
        'vita_rae_mcg',
        'thia_mg',
        'ribo_mg',
        'niac_mg',
        'vitb6_mg',
        'folate_mcg',
        'vitb12_mcg',
        'fe_mg',
        'zn_mg'
      )) %>% 
      mutate(sd = ifelse(nutrient == "vita_rae_mcg",
        0.2*ear_value, ifelse(nutrient == "niac", 0.15*ear_value, 0.1*ear_value)
        ))
    
    #calculate the normal distribution 
    normal = rnorm(n = 1000, mean = y$ear_value[[which(y$nutrient == {{micronutrient}})]], sd =  y$sd[[which(y$nutrient == {{micronutrient}})]])
    
    #create a list of the normal distribution in order 
    ordered_normal = normal[order(normal)]
    return(ordered_normal)
  }
  
  ordered_normal = micronutrient_normal(micronutrient)
  
  # find where the position of where the intake is relative to a normal distribution
  # around 
  if(length(which(ref_value>ordered_normal)) == 0){
    position = 1
  }else {
    position = max(which(ref_value>ordered_normal))
  }
  
  p <- 0
  
  if(position == 1){
    p = 0
  } else if(position == number_dist){p = 1
  } else {
    p = position/number_dist
    p
  }

  return(p)

}
# need to vectorise to be able to use within  dplyr
calculate_adequacy_prob <- Vectorize(calculate_adequacy_prob)



mean_nutrient_density <- function(df){
  
  allen_ear <- allen_ear %>% 
    mutate(nut_ear_value = ear_value/2.100)

  
  
  final_df <- df  %>%
    pivot_longer(-c(hhid,energy_kcal), names_to = "nutrient") %>% 
    right_join(allen_ear, by= "nutrient") %>% 
    filter(nutrient %in% c(
      'vita_rae_mcg',
      'thia_mg',
      'ribo_mg',
      'niac_mg',
      'vitb6_mg',
      'folate_mcg',
      'vitb12_mcg',
      'fe_mg',
      'zn_mg'
    )) %>% 
    mutate(nut_dens = value/(energy_kcal/1000)) %>% 
    mutate(nut_dens_ratio = nut_dens/nut_ear_value) %>% 
    group_by(hhid) %>% 
    summarise(mean_nut_dens = mean(nut_dens_ratio))
  
  return(final_df)
  
}
```

# Calculating PA for Ethiopia 

```{r}

pa <- df %>%
    pivot_longer(-hhid, names_to = "nutrient") %>% 
    filter(nutrient %in% c(
      'vita_rae_mcg',
      'thia_mg',
      'ribo_mg',
      'niac_mg',
      'vitb6_mg',
      'folate_mcg',
      'vitb12_mcg',
      'fe_mg',
      'zn_mg'
    )) %>% 
    mutate(adequacy_prob = calculate_adequacy_prob(value, nutrient)) %>% 
    group_by(hhid)
  
  # %>%     summarize(mpa = mean(adequacy_prob)) 

```


```{r}
eth_pa <- pa %>%
  pivot_wider(names_from = nutrient,
              values_from = c(value, adequacy_prob),
              names_sep = "_",
              values_fn = list(value = max, adequacy_prob = max)) %>% 
  select(adequacy_prob_vita_rae_mcg, 
         adequacy_prob_thia_mg,
         adequacy_prob_ribo_mg,
         adequacy_prob_niac_mg,
         adequacy_prob_vitb6_mg,
         adequacy_prob_folate_mcg,
         adequacy_prob_vitb12_mcg, 
         adequacy_prob_fe_mg,
         adequacy_prob_zn_mg)
        

eth_pa_nar <- inner_join(eth, eth_pa)
```

```{r}

# Checking that it is correct
eth_pa_nar %>% 
  mutate(mpa2 = rowMeans(select(., adequacy_prob_vita_rae_mcg, adequacy_prob_thia_mg,
         adequacy_prob_ribo_mg,
         adequacy_prob_niac_mg,
         adequacy_prob_vitb6_mg,
         adequacy_prob_folate_mcg,
         adequacy_prob_vitb12_mcg, 
         adequacy_prob_fe_mg, adequacy_prob_zn_mg), na.rm = TRUE)) %>% 
  select(mpa, mpa2) %>% 
  round(2)


# Renaming columns
eth_pa_nar <- eth_pa_nar %>% 
  rename(vita_rae_pa = adequacy_prob_vita_rae_mcg, 
         thia_pa = adequacy_prob_thia_mg,
         ribo_pa = adequacy_prob_ribo_mg,
         niac_pa = adequacy_prob_niac_mg,
         vitb6_pa = adequacy_prob_vitb6_mg, 
         folate_pa = adequacy_prob_folate_mcg,
         vitb12_pa = adequacy_prob_vitb12_mcg,
         fe_pa = adequacy_prob_fe_mg,
         zn_pa = adequacy_prob_zn_mg)


write.csv(eth_pa_nar, file = "eth_nar_pa.csv", row.names = TRUE)
```
# India 
```{r}
df <- ind %>% 
  select(hhid, energy_kcal, vita_rae_mcg, thia_mg, ribo_mg, niac_mg, vitb6_mg, folate_mcg, vitb12_mcg, fe_mg, zn_mg)


pa <- df %>%
    pivot_longer(-hhid, names_to = "nutrient") %>% 
    filter(nutrient %in% c(
      'vita_rae_mcg',
      'thia_mg',
      'ribo_mg',
      'niac_mg',
      'vitb6_mg',
      'folate_mcg',
      'vitb12_mcg',
      'fe_mg',
      'zn_mg'
    )) %>% 
    mutate(adequacy_prob = calculate_adequacy_prob(value, nutrient)) %>% 
    group_by(hhid)
  
  # %>%     summarize(mpa = mean(adequacy_prob)) 

```


```{r}
ind_pa <- pa %>%
  pivot_wider(names_from = nutrient,
              values_from = c(value, adequacy_prob),
              names_sep = "_",
              values_fn = list(value = max, adequacy_prob = max)) %>% 
  select(adequacy_prob_vita_rae_mcg, 
         adequacy_prob_thia_mg,
         adequacy_prob_ribo_mg,
         adequacy_prob_niac_mg,
         adequacy_prob_vitb6_mg,
         adequacy_prob_folate_mcg,
         adequacy_prob_vitb12_mcg, 
         adequacy_prob_fe_mg,
         adequacy_prob_zn_mg)
        

ind_pa_nar <- inner_join(ind, ind_pa)

```

```{r}

# Checking that it is correct
ind_pa_nar %>% 
  mutate(mpa2 = rowMeans(select(., adequacy_prob_vita_rae_mcg, adequacy_prob_thia_mg,
         adequacy_prob_ribo_mg,
         adequacy_prob_niac_mg,
         adequacy_prob_vitb6_mg,
         adequacy_prob_folate_mcg,
         adequacy_prob_vitb12_mcg, 
         adequacy_prob_fe_mg, adequacy_prob_zn_mg), na.rm = TRUE)) %>% 
  select(mpa, mpa2) %>% 
  round(2)


# Renaming columns
ind_pa_nar <- ind_pa_nar %>% 
  rename(vita_rae_pa = adequacy_prob_vita_rae_mcg, 
         thia_pa = adequacy_prob_thia_mg,
         ribo_pa = adequacy_prob_ribo_mg,
         niac_pa = adequacy_prob_niac_mg,
         vitb6_pa = adequacy_prob_vitb6_mg, 
         folate_pa = adequacy_prob_folate_mcg,
         vitb12_pa = adequacy_prob_vitb12_mcg,
         fe_pa = adequacy_prob_fe_mg,
         zn_pa = adequacy_prob_zn_mg)


write.csv(ind_pa_nar, file = "ind_nar_pa.csv", row.names = TRUE)

```

# Nigeria 
```{r}
df <- nga %>% 
  select(hhid, energy_kcal, vita_rae_mcg, thia_mg, ribo_mg, niac_mg, vitb6_mg, folate_mcg, vitb12_mcg, fe_mg, zn_mg)


pa <- df %>%
    pivot_longer(-hhid, names_to = "nutrient") %>% 
    filter(nutrient %in% c(
      'vita_rae_mcg',
      'thia_mg',
      'ribo_mg',
      'niac_mg',
      'vitb6_mg',
      'folate_mcg',
      'vitb12_mcg',
      'fe_mg',
      'zn_mg'
    )) %>% 
    mutate(adequacy_prob = calculate_adequacy_prob(value, nutrient)) %>% 
    group_by(hhid)
  
  # %>%     summarize(mpa = mean(adequacy_prob)) 

```


```{r}
nga_pa <- pa %>%
  pivot_wider(names_from = nutrient,
              values_from = c(value, adequacy_prob),
              names_sep = "_",
              values_fn = list(value = max, adequacy_prob = max)) %>% 
  select(adequacy_prob_vita_rae_mcg, 
         adequacy_prob_thia_mg,
         adequacy_prob_ribo_mg,
         adequacy_prob_niac_mg,
         adequacy_prob_vitb6_mg,
         adequacy_prob_folate_mcg,
         adequacy_prob_vitb12_mcg, 
         adequacy_prob_fe_mg,
         adequacy_prob_zn_mg)
        

nga_pa_nar <- inner_join(nga, nga_pa)


```

```{r}

# Checking that it is correct
nga_pa_nar %>% 
  mutate(mpa2 = rowMeans(select(., adequacy_prob_vita_rae_mcg, adequacy_prob_thia_mg,
         adequacy_prob_ribo_mg,
         adequacy_prob_niac_mg,
         adequacy_prob_vitb6_mg,
         adequacy_prob_folate_mcg,
         adequacy_prob_vitb12_mcg, 
         adequacy_prob_fe_mg, adequacy_prob_zn_mg), na.rm = TRUE)) %>% 
  select(mpa, mpa2) %>% 
  round(2)


# Renaming columns
nga_pa_nar <- nga_pa_nar %>% 
  rename(vita_rae_pa = adequacy_prob_vita_rae_mcg, 
         thia_pa = adequacy_prob_thia_mg,
         ribo_pa = adequacy_prob_ribo_mg,
         niac_pa = adequacy_prob_niac_mg,
         vitb6_pa = adequacy_prob_vitb6_mg, 
         folate_pa = adequacy_prob_folate_mcg,
         vitb12_pa = adequacy_prob_vitb12_mcg,
         fe_pa = adequacy_prob_fe_mg,
         zn_pa = adequacy_prob_zn_mg)


write.csv(nga_pa_nar, file = "nga_nar_pa.csv", row.names = TRUE)
```






