---
title: "obj2"
output: html_document
date: "2024-07-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# How do the composite indicators relate to each individual micro-nutrient?

How are mar and mpa correlated with nutrient adequacy ratios (NARs)?
Which micronutrients are best represented in the composite indicators?
Which micronutrients are worst represented in the composite indicators?
Why?

```{r}
library(tidyverse)
library(ggpubr)
library(ggcorrplot)

eth<- read.csv("eth_nar.csv")
ind<- read.csv("ind_nar.csv") 
nga<- read.csv("nga_nar.csv")
```

```{r}
# Ethiopia

eth_cor <- cor(eth[c("vita_rae_nar",
                     "thia_nar",
                     "ribo_nar",
                     "niac_nar",
                     "vitb6_nar",
                     "folate_nar",
                     "vitb12_nar",
                     "fe_nar",
                     "zn_nar",
                     "mar",
                     "mpa")], method = "spearman")
as.data.frame(eth_cor) %>% select(mar, mpa)


# Ethiopia Urban 
eth_urban <- eth %>%
  filter(res == "Urban")

eth_cor_u <- cor(eth_urban[c("vita_rae_nar",
                     "thia_nar",
                     "ribo_nar",
                     "niac_nar",
                     "vitb6_nar",
                     "folate_nar",
                     "vitb12_nar",
                     "fe_nar",
                     "zn_nar",
                     "mar",
                     "mpa")], method = "spearman")
as.data.frame(eth_cor_u) %>% select(mar, mpa)

# Ethiopia Rural 
# I don't know why it only shows NA values...
eth_rural <- eth %>%
  filter(res == "Rural")


# correlation matrix of individual PA for each micro nutrient, mar,  mpa 


eth_cor_r <- cor(eth_rural[c("vita_rae_nar",
                     "thia_nar",
                     "ribo_nar",
                     "niac_nar",
                     "vitb6_nar",
                     "folate_nar",
                     "vitb12_nar",
                     "fe_nar",
                     "zn_nar",
                     "mar",
                     "mpa")], method = "spearman")
as.data.frame(eth_cor_r)

```
```{r}
#  Vitamin A NAR and MAR

ggplot(eth, aes(x = mar, y = log(vita_rae_nar)))+
  geom_point(alpha = .2)
```


```{r}
#India
ind_cor <- cor(ind[c("vita_rae_nar",
                       "thia_nar",
                       "ribo_nar",
                       "niac_nar",
                       "vitb6_nar",
                       "folate_nar",
                       "vitb12_nar",
                       "fe_nar",
                       "zn_nar",
                       "mar",
                       "mpa")],
               method = "spearman")
as.data.frame(ind_cor) %>% select(mar, mpa)


# Note very high or very low correlations
  # mar: high > .7 (riboflavin, niacin, vitb6, folate, vitb12, iron, zinc), low < .5 (thiamin)
  # mpa : high > .7 (riboflavin, niacin, vitb6, folate, iron, zinc), low < .5 (vitA, thiamin)



# India Urban 
ind_urban <- ind %>%
  filter(res == "Urban")

ind_cor_u <- cor(ind_urban[c("vita_rae_nar",
                     "thia_nar",
                     "ribo_nar",
                     "niac_nar",
                     "vitb6_nar",
                     "folate_nar",
                     "vitb12_nar",
                     "fe_nar",
                     "zn_nar",
                     "mar",
                     "mpa")], method = "spearman")
as.data.frame(ind_cor_u) %>% select(mar, mpa)

# India Rural 
ind_rural <- ind %>%
  filter(res == "Rural")

ind_cor_r <- cor(ind_rural[c("vita_rae_nar",
                     "thia_nar",
                     "ribo_nar",
                     "niac_nar",
                     "vitb6_nar",
                     "folate_nar",
                     "vitb12_nar",
                     "fe_nar",
                     "zn_nar",
                     "mar",
                     "mpa")], method = "spearman")
as.data.frame(ind_cor_r) %>% select(mar, mpa)


```

```{r}
#Nigeria
nga_cor <- cor(nga[c("vita_rae_nar",
                       "thia_nar",
                       "ribo_nar",
                       "niac_nar",
                       "vitb6_nar",
                       "folate_nar",
                       "vitb12_nar",
                       "fe_nar",
                       "zn_nar",
                       "mar",
                       "mpa")],
               method = "spearman")
as.data.frame(nga_cor) %>% select(mar, mpa)


# Note very high or very low correlations
  # mar: high > .7 (all, b12 is just moderate) low < .5 (vitamin A)
  # mpa : high > .7 (all but b12 is moderate), low < .5 (vitamin A)

#Nigeria - mar and mpa produce remarkably similar correlations 



# Nigeria Urban 
nga_urban <- nga %>%
  filter(res == "Urban")

nga_cor_u <- cor(nga_urban[c("vita_rae_nar",
                     "thia_nar",
                     "ribo_nar",
                     "niac_nar",
                     "vitb6_nar",
                     "folate_nar",
                     "vitb12_nar",
                     "fe_nar",
                     "zn_nar",
                     "mar",
                     "mpa")], method = "spearman")
as.data.frame(nga_cor_u) %>% select(mar, mpa)

# Nigeria Rural 
nga_rural <- nga %>%
  filter(res == "Rural")

nga_cor_r <- cor(nga_rural[c("vita_rae_nar",
                     "thia_nar",
                     "ribo_nar",
                     "niac_nar",
                     "vitb6_nar",
                     "folate_nar",
                     "vitb12_nar",
                     "fe_nar",
                     "zn_nar",
                     "mar",
                     "mpa")], method = "spearman")
as.data.frame(nga_cor_r) %>% select(mar, mpa)


```

# Visualize the correlation matrix
```{r}
# Ethiopia 
ggcorrplot(eth_cor, hc.order = F, type = "lower",
           lab = TRUE, lab_size = 3, method="circle",
           colors = c("red", "white", "blue"), title="Correlogram",
           ggtheme=theme_minimal())
```
```{r}
# India 
ggcorrplot(ind_cor, hc.order = F, type = "lower",
           lab = TRUE, lab_size = 3, method="circle",
           colors = c("red", "white", "blue"), title="Correlogram",
           ggtheme=theme_minimal())
```

```{r}
# Nigeria 
ggcorrplot(nga_cor, hc.order = F, type = "lower",
           lab = TRUE, lab_size = 3, method="circle",
           colors = c("red", "white", "blue"), title="Correlogram",
           ggtheme=theme_minimal())
```
```{r}
#  Food Groups 
  # By type 
  # Animal source foods, vegetables, fruits - MN coming from these foods
  # Reconstruct the MAR and NARs with different micro nutrients to see of certain food groups will be better represented with specific micro nutrients 

  # MAR/MPA - staple grains (thiamin, niacin, vitb6, fe, zn)
  # MAR/MPA - nutrient dense foods (ribo, vitb12, vitA, folate)
```

